# Generated by Django 4.1.1 on 2022-09-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.CharField(max_length=100)),
                ('done', models.BooleanField()),
                ('day', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
